name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: macOS-15 
    env:
      SWIFT_VERSION: 6.0
    name: Build and Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Install Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Get swift version
        run: swift --version  

      - name: Run Swift Package Tests
        run: xcodebuild test -scheme SimpleAuthenticationServices-Package -destination 'platform=macOS'
